typedef struct tab_channel_type Tchan;
typedef struct tab2channel_type T2chan;
typedef struct tab_current_type Tcurr;
struct olf_receptor_type {
 char *name; int index; struct object_type *object; short flags; short nextfields; char **extfields; float x; float y; float z; unsigned int nmsgin; Msg *msgin; Msg *msgintail; unsigned int nmsgout; Msg *msgout; Msg *msgouttail; GenesisObject *compositeobject; Element *componentof; Element *parent; Element *child; Element *next; float activation;
 float response[10];
 float Vm;
 float Vmin;
 float Vmax;
 float max_rate;
 float min_rate;
 float state;
 float gain;
 int transfer_form;
};
struct olf_receptor2_type {
 char *name; int index; struct object_type *object; short flags; short nextfields; char **extfields; float x; float y; float z; unsigned int nmsgin; Msg *msgin; Msg *msgintail; unsigned int nmsgout; Msg *msgout; Msg *msgouttail; GenesisObject *compositeobject; Element *componentof; Element *parent; Element *child; Element *next; float activation; double Ik; double Gk; float Ek;
 float *response;
 float modulation;
 int nodors;
 short allocated;
 double X,Y;
 float tau1;
 float tau2;
 float gmax;
 double xconst1;
 double xconst2;
 double yconst1;
 double yconst2;
 float norm;
};
struct tab_gate_type {
    char *name; int index; struct object_type *object; short flags; short nextfields; char **extfields; float x; float y; float z; unsigned int nmsgin; Msg *msgin; Msg *msgintail; unsigned int nmsgout; Msg *msgout; Msg *msgouttail; GenesisObject *compositeobject; Element *componentof; Element *parent; Element *child; Element *next; float activation;
    double m;
 struct interpol_struct *alpha;
 short alpha_alloced;
 struct interpol_struct *beta;
 short beta_alloced;
    short instantaneous;
};
struct table_type {
 char *name; int index; struct object_type *object; short flags; short nextfields; char **extfields; float x; float y; float z; unsigned int nmsgin; Msg *msgin; Msg *msgintail; unsigned int nmsgout; Msg *msgout; Msg *msgouttail; GenesisObject *compositeobject; Element *componentof; Element *parent; Element *child; Element *next;
 double input;
 double output;
 struct interpol_struct *table;
 short alloced;
 short step_mode;
 double stepsize;
};
struct table2d_type {
    char *name; int index; struct object_type *object; short flags; short nextfields; char **extfields; float x; float y; float z; unsigned int nmsgin; Msg *msgin; Msg *msgintail; unsigned int nmsgout; Msg *msgout; Msg *msgouttail; GenesisObject *compositeobject; Element *componentof; Element *parent; Element *child; Element *next;
    double input;
    double input2;
    double output;
    double negoutput;
    struct interpol2d_struct *table;
    short alloced;
    short step_mode;
    double stepsize;
};
struct tab_channel_type {
    char *name; int index; struct object_type *object; short flags; short nextfields; char **extfields; float x; float y; float z; unsigned int nmsgin; Msg *msgin; Msg *msgintail; unsigned int nmsgout; Msg *msgout; Msg *msgouttail; GenesisObject *compositeobject; Element *componentof; Element *parent; Element *child; Element *next; float activation; double Ik; double Gk; float Ek;
    float Gbar; double X; double Y; double Z; float Xpower; float Ypower; float Zpower; short instant; short X_alloced; short Y_alloced; short Z_alloced; float surface; short Z_conc;
    struct interpol_struct *X_A;
    struct interpol_struct *X_B;
    struct interpol_struct *Y_A;
    struct interpol_struct *Y_B;
    struct interpol_struct *Z_A;
    struct interpol_struct *Z_B;
};
struct tab2channel_type {
    char *name; int index; struct object_type *object; short flags; short nextfields; char **extfields; float x; float y; float z; unsigned int nmsgin; Msg *msgin; Msg *msgintail; unsigned int nmsgout; Msg *msgout; Msg *msgouttail; GenesisObject *compositeobject; Element *componentof; Element *parent; Element *child; Element *next; float activation; double Ik; double Gk; float Ek;
    float Gbar; double X; double Y; double Z; float Xpower; float Ypower; float Zpower; short instant; short X_alloced; short Y_alloced; short Z_alloced; float surface; short Z_conc;
    short Xindex;
    short Yindex;
    short Zindex;
    struct interpol2d_struct *X_A;
    struct interpol2d_struct *X_B;
    struct interpol2d_struct *Y_A;
    struct interpol2d_struct *Y_B;
    struct interpol2d_struct *Z_A;
    struct interpol2d_struct *Z_B;
};
struct tab_current_type {
    char *name; int index; struct object_type *object; short flags; short nextfields; char **extfields; float x; float y; float z; unsigned int nmsgin; Msg *msgin; Msg *msgintail; unsigned int nmsgout; Msg *msgout; Msg *msgouttail; GenesisObject *compositeobject; Element *componentof; Element *parent; Element *child; Element *next; float activation; double Ik; double Gk; float Ek;
    float Gbar;
    short Gindex;
    short alloced;
    float surface;
    struct interpol2d_struct *G_tab;
    struct interpol2d_struct *I_tab;
};
struct disk_in_type {
 char *name; int index; struct object_type *object; short flags; short nextfields; char **extfields; float x; float y; float z; unsigned int nmsgin; Msg *msgin; Msg *msgintail; unsigned int nmsgout; Msg *msgout; Msg *msgouttail; GenesisObject *compositeobject; Element *componentof; Element *parent; Element *child; Element *next; float activation;
 FILE *fp;
 char *filename;
 short fileformat;
 char *tempdata;
 float start_time;
 float dt;
 int datatype;
 int header_size;
 float time_offset;
 short is_open;
 short leave_open;
 long lastpos;
 short loop;
 int nx,ny;
 short allocated;
 float **val;
 struct interpol_struct *xpts;
 struct interpol_struct *ypts;
 struct interpol_struct *zpts;
};
struct dd_syn_type {
 char *name; int index; struct object_type *object; short flags; short nextfields; char **extfields; float x; float y; float z; unsigned int nmsgin; Msg *msgin; Msg *msgintail; unsigned int nmsgout; Msg *msgout; Msg *msgouttail; GenesisObject *compositeobject; Element *componentof; Element *parent; Element *child; Element *next; float activation; double Ik; double Gk; float Ek;
 struct interpol_struct *transf;
 short transf_alloced;
 float gmax;
 double X,Y;
 float tau1;
 float tau2;
 double xconst1;
 double xconst2;
 double yconst1;
 double yconst2;
 float norm;
};
